spring:
  application:
    name: @project.name@

openweathermap:
  url: https://api.openweathermap.org/data/2.5/forecast?q=&appid=d2929e9483efc82c82c32ee7e02d563e&units=metric&cnt=10
springdoc:
  swagger-ui:
    use-root-path: true
server:
  servlet:
    context-path: /@project.name@
